default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('SHOPIFY_APP_DATABASE_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('SHOPIFY_APP_DATABASE_PASSWORD') { 'password' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shopify_app_development

test:
  <<: *default
  database: shopify_app_test

production:
  <<: *default
  database: shopify_app_production
  username: shopify_app
  password: <%= ENV['SHOPIFY_APP_DATABASE_PASSWORD'] %>
